### ISSUE TITLE
Rework section 3: Listing sensitive taxa

### ISSUE THREAD

**Issue by ahahn-gbif** [gbif/doc-sensitive-species-best-practices#12]
This section, in paragraph 1, names a recognized concern. However, the following part is leaving the area of "Current Best Practices" and is reaching over into the scoping of potentially desirable future work, making recommendations. This is preempting the outcome of some discussions still to be had (areas of responsibility, design decisions, data flow i.a.). 

Within the context of this document, recommend to stay focused on current best practices, and omit any parts that sketch out potential future work or recommendations, as we are not in a position yet to commit to exactly this solution. Suggest to cut back to mentioning that no global mechanism to handle this issue currently exist, and that we can expect further discussions on how to best approach this recognized area of concern.

**Comment by ArthurChapman** [comment]
Thanks @ahahn-gbif. This becomes difficult to implement as to do this throughout the document would require a complete rewrite. Perhaps we need to change the title to something like "Recommended Best Practices ...]. The problem is that, with few exceptions, very few institutions/countries are implementing any of this, so in reality - nearly everything is a recommendation rather than what is currently in practice.   

In the original workshops (organised and funded by GBIF), there was a strong recommendation that such a list be developed and incorporated someway into the GBIF Backbone - something like IUCN's endangered species.

I can rewrite this paragraph, but to universally remove all such recommendations for future would not be at all practical (or, in my mind, worthwhile).

@kcopas I am wondering if we should change the Title to "Recommended Best Practices for Generalizing Sensitive Species Occurrence Data" which probably reflects better the contents.  It would mean rewording a fewe things in the introduction, but otherwise ....   Only other issue would be changing the references in the Georeferencing Best Practices.

**Comment by laurarussell** [comment]
Moved listing of taxa to the Afterword section with edits in Pull Request #15 .
