### ISSUE TITLE
Emphasize importance of sharing a coordinate uncertanity

### ISSUE THREAD

**Issue by MattBlissett** [gbif/doc-sensitive-species-best-practices#22]
I think we've had users overlook or completely misunderstand the need to include a coordinate uncertainy after generalization, perhaps because section 4.1 refers to limitations in DWC, or perhaps because uncertainty is only briefly mentioned in that section.

Could we add something to the Georeference column of table 7, or a sub-section explaining how to calculate uncertainty in metres after rounding to the nearest degree?

https://docs.gbif.org/sensitive-species-best-practices/master/en/index.en.html#table-07

**Comment by ArthurChapman** [comment]
Perhaps best add a sentence in Section #4.2

Good practice dictates that whatever you do to generalize the data that you document it so that users of the data know what reliance they can place in it. **Note, that when documenting what has been done, it is essential that both the coordinates and the coordinate uncertainty in meters be recorded. How this is best done can be seen in the Georeferencing Quick Reference Guide (Zermoglio et al. 2020).**

Also - another reference needs top be added to the References.

**Zermoglio PFF, Chapman AD, Wieczorek JR, Luna MC, Bloom DA (2020) Georeferencing Quick References Guide Copenhagen: Copenhagen: GBIF Secretariat. https://doi.org/10.35035/e09p-h128.**
