### ISSUE TITLE
Land ownership restrictions?

### ISSUE THREAD

**Issue by tkarim** [gbif/doc-sensitive-species-best-practices#4]
After reading through the revised document (which is great by the way and addresses many issues being discussed in the paleo community) I am wondering if something needs to be added about having to denature locality information due to land ownership restrictions. For example, in the USA if a fossil specimen was collected on federal land (Forest service, National Parks, etc) there are laws ([PRPA](https://irma.nps.gov/DataStore/Reference/Profile/2274127)) restricting data providers (e.g. collection) from sharing that data. We have heard from some federal agencies and they are developing implementation guidelines for PRPA that would recommend, perhaps, allowing us to share lat/long truncated to .1 degrees or maybe a county level georeference. Should these types of land owner-focused situations be included in the revised document? As is, the document is very focused on the sensitive nature of the taxon versus the sensitive nature of the locality.

**Comment by ArthurChapman** [comment]
Thanks @tkarim.  I will check the document again, and may add something to the introduction. I have deliberately addressed taxon sensitivity as to go broader adds a lot of extra issues, including land privacy, personal privacy, etc.  I didn't want to go into these in depth - firstly because different jurisdictions (countries/states, etc.) have quite different legislation with regard to land privacy.  Secondly personal privacy is a huge issue being covered again by many legal jurisdictions.  The area not being covered is that of taxon sensitivity.  Bearing that in mind, however, I would recommend, wherever possible, to follow the same principles of generalization over other methods such as randomization. If the data can be restricted by generalization (for example to 0.1 degree - this would be consistent with my recommendations.

I will look at the document again and see if I should add a note.  Thanks again

**Comment by ArthurChapman** [comment]
@kcopas 

Under _Scope_  Add a paragraph at the end of section

This document only looks at taxon sensitivity and not sensitivity related to issues such as land or personal privacy. Different jurisdictions (countries and states) have quite diverse legislation with regard to both land and personal privacy. The topic not being covered is that of taxon sensitivity. Bearing that in mind, however, I would recommend, wherever possible, to follow the same principles of generalization recommended in this publication over other methods such as randomization.
