### ISSUE TITLE
Generalization 

### ISSUE THREAD

**Issue by andrewrodrigues** [gbif/doc-sensitive-species-best-practices#6]
In https://docs.gbif-uat.org/sensitive-species-best-practices/master/en/#s-generalization you recommend a gridded approach to releasing sensitive data.  However, when you categorize sensitive species you recommend decreasing the precision of records implying increasing the radius within which the observation might have been made.  I´m unsure what is the recommended protocol.

**Comment by ArthurChapman** [comment]
Decreasing the precision does not mean, in the case of decimal degrees, reducing a radius. It means reducing the precision - i.e. the number of decimal places in the decimal degrees.  I may make this clearer by using __coordinate precision__ rather than __precision__.  Of course, reducing the precision at publication, would increase the uncertainty (which is a radius using the point-radius method) - however, I recommend that the true location be retained in the database and thus the true uncertainty would not change.

The definitions from the book Georeferencing Best Practices which is soon to be published are:

__precision__
the closeness of a repeated set of observations of the same quantity to one another – a measure of control over random error.

with values, it describes the finest unit of measurement used to express that value (e.g. if a record is reported to the nearest second, the precision is 1/3600th of a degree; if a decimal degree is reported to two decimal places, the precision is 0.01 of a degree).

__coordinate precision__
the fraction of a degree corresponding to the number of significant digits in the source coordinates. For example, if the coordinates are reported to the nearest minute, the precision is 1/3600th (0.00027778) of a degree; if a decimal degree is reported to two decimal places, the precision is 0.01 of a degree.

**Comment by ArthurChapman** [comment]
@kcopas 

1. __Table 8__  under __precisionDataProvided___ change the second "precision" to "coordinate precision" i.e. "The scale or the precision of the data made available via the Darwin Core record – may be done as precision" to "The scale or the precision of the data made available via the Darwin Core record – may be done as coordinate precision"

2. __Table 8__  under __precisionDataStored___ change the second "precision" to "coordinate precision" i.e. "The scale or the precision of the data stored or retained by the data custodian – may be done as precision" to "The scale or the precision of the data stored or retained by the data custodian – may be done as coordinate precision"

3. under __§Glossary__

add

__precision__
describes the finest unit of measurement used to express a value (e.g. if a record is reported to the nearest second, the precision is 1/3600th of a degree; if a decimal degree is reported to two decimal places, the precision is 0.01 of a degree).


NB I am confident that all other uses of precision are self explanatory.
